name = "hello"
version = "1.0.0"
type = "normal"
description = "A hello world program (glibc)"
install_script = "install.lua"
source = "./packages/hello-1.0.0.tar.gz"

[authors]
afroraydude = "afroraydude@protonmail.com"
